### ISSUE TITLE
TypeError while running recovery

### ISSUE THREAD

**Issue by ankur3k** [andreapizzato/tez-recovery#2]
Hi there,

I am getting a TypeError and while running recovery script and here is the traceback:

TypeError: library.sodium.crypto_sign_seed_keypair is not a function
    at Object.generateKeys (/Users/ankursharma/Downloads/tez-recovery-master/lib/eztz.cli.js:294:31)
    at TezosBF.__checkPassword (/Users/ankursharma/Downloads/tez-recovery-master/src/tezosbf.js:75:28)
    at TezosBF.__checkNextPassword (/Users/ankursharma/Downloads/tez-recovery-master/src/tezosbf.js:107:8)
    at TezosBF.find (/Users/ankursharma/Downloads/tez-recovery-master/src/tezosbf.js:125:8)
    at doRecovery (/Users/ankursharma/Downloads/tez-recovery-master/src/commands/recovery.js:68:11)
    at figlet (/Users/ankursharma/Downloads/tez-recovery-master/src/index.js:30:7)
    at /Users/ankursharma/Downloads/tez-recovery-master/node_modules/figlet/lib/figlet.js:710:13
    at /Users/ankursharma/Downloads/tez-recovery-master/node_modules/figlet/lib/node-figlet.js:24:13
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

Could you please take a look?

Thanks much!

**Comment by ankur3k** [comment]
Hi there, could you please help me out with this?

Thanks much!
-Ankur

**Comment by mouser98** [comment]
I'm having the identical problem.  Need some help please.  Thanks in advance

**Comment by hh221165** [comment]
I'am having the same problem. Any advice?

**Comment by hh221165** [comment]
>           I'm having the same problem. Any advice?

I got it working under Ubuntu

**Comment by Bradfrogger** [comment]
> I'm having the same problem. Any advice?
> 
> 
> I got it working under Ubuntu

Was it just a matter of running the recovery tool in that environment?

**Comment by adamlawson50** [comment]
I have this issue - anyone manage to work out what the problem was ? I am in windows

**Comment by Bradfrogger** [comment]
My issue was simply password. I followed the ICO instructions and created a unique password, different from the authentication. Luckily, I had written the password down.. Tezos retrieved!

**Comment by adamlawson50** [comment]
I am trying to get my ico tezos to an exchange and stuck ! Trying to get to TezBox then plan to go to kraken but I can’t get to TezBox, the only thing I’m not 100% certain of is my password...  

On 12 May 2019, at 21:59, Bradfrogger <notifications@github.com> wrote:

My issue was simply password. I followed the ICO instructions and created a unique password, different from the authentication. Luckily, I had written the password down.. Tezos retrieved!

**Comment by adamlawson50** [comment]
anyone got the TypeError issue resolved ?

**Comment by ankur3k** [comment]
Not me. Still struggling. Please help guys. My brother’s money is stuck in this damn coin.

**Comment by hh221165** [comment]
The Telegram Group called "Tezos XTZ Recovery" seems to be very helpful.  
https://t.me/xtzrecovery

I created my own tool which helped me to recover my password. You can try it if you want. You can find it at:
https://github.com/hh221165/TEZOS_ICO_PASSWORD_RECOVERY_TOOL

Good luck

**Comment by andreapizzato** [comment]
Hi there, will definitely take a look at it.

**Comment by andreapizzato** [comment]
Ok, found the culprit. It was about EZTZ being updated and a misalignment on dependencies packages.

Please try downloading the last 1.3.0 release of this tool, re-install it and it should work out of the box.

**Comment by ankur3k** [comment]
Thanks AndreaPizzato. I’ll try if this new solution works. I really hope it does 🙏

**Comment by mouser98** [comment]
So I sort of got it working but when I start the recovery I get a
"Deprecation Warning."  My screen looks like this:

[image: tezos password crack.JPG]

So my question is, is the program still running and should I just be
patient, or do I need to wait until the buffer() problem is fixed?

Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by ankur3k** [comment]
Hey guys! I see the same issue
;
0% | ETA: 0s | 0/5(node:850) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.al

I am not sure if the program does anything past this step or is it just stuck because of the buffer error. Could you please help? I'd really appreciate it.

**Comment by ankur3k** [comment]
Hi AndreaPizzato,

Hope you’re doing well. Could you please look into this error that’s stopping me and a few other folks from moving forward with Tezos password recovery?

Thanks much,
Ankur

**Comment by mouser98** [comment]
Hey, do you know that Tezos Foundation has a password recovery service?
https://recovery.tezos.com/

**Comment by ankur3k** [comment]
Yeah, I found out about it. Would this be the same as the solution provided
here? Also, were you able to recover your password with the Tezos
foundation's solution?

-Ankur

**Comment by mouser98** [comment]
Not yet. They're working on it.  What is weird for me is I know what
password I used, it just doesn't work now.

**Comment by ankur3k** [comment]
That’s even more messed up. They haven’t been able to recover mine either. They’re working on it(at least that’s what they say)
